version: '3.6'

networks:
  kafka:
    driver: bridge

services:
  zksrv:
    hostname: zksrv
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka
  kmgr:
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    environment:
      - 'ZK_HOSTS=zksrv:2181'
      - 'APPLICATION_SECRET=letmein'
    depends_on:
      - zksrv
    networks:
      - kafka
  ksrv1:
    hostname: ksrv1
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - 'KAFKA_CFG_BROKER_ID=1'
      - 'KAFKA_CFG_ZOOKEEPER_CONNECT=zksrv:2181'
      - 'KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://ksrv1:19092'
      - 'KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT'
      - 'KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_INTERNAL://:19092'
      - 'KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT_INTERNAL'
      - 'ALLOW_PLAINTEXT_LISTENER=yes'
    depends_on:
      - zksrv
    networks:
      - kafka
  ksrv2:
    hostname: ksrv2
    image: 'bitnami/kafka:latest'
    ports:
      - '9093:9092'
    environment:
      - 'KAFKA_CFG_BROKER_ID=2'
      - 'KAFKA_CFG_ZOOKEEPER_CONNECT=zksrv:2181'
      - 'KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093,PLAINTEXT_INTERNAL://ksrv2:19093'
      - 'KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT'
      - 'KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_INTERNAL://:19093'
      - 'KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT_INTERNAL'
      - 'ALLOW_PLAINTEXT_LISTENER=yes'
    depends_on:
      - zksrv
    networks:
      - kafka
  rest:
    image: confluentinc/cp-kafka-rest:5.4.0
    depends_on:
      - zksrv
      - ksrv1
      - ksrv2
    ports:
      - 8082:8082
    hostname: rest
    container_name: rest
    environment:
      - 'KAFKA_REST_HOST_NAME=rest'
      - 'KAFKA_REST_BOOTSTRAP_SERVERS=PLAINTEXT_INTERNAL://ksrv1:19092,PLAINTEXT_INTERNAL://ksrv2:19093'
      - 'KAFKA_REST_LISTENERS=http://0.0.0.0:8082'
    networks:
      - kafka
  jdbc:
    hostname: jdbc
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_DATABASE=topics'
      - 'MYSQL_USER=username'
      - 'MYSQL_PASSWORD=password'
    networks:
      - kafka
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - kafka
  jupyter-spark:
    image: jupyter/all-spark-notebook
    hostname: jupyter-spark
    volumes:
      - ./spark:/home/jovyan/spark
    ports:
      - 8889:8888
      - 4040:4040
    networks:
      - kafka
